[env]
# for building librime-sys
LIBRIME_INCLUDE_DIR = "${CARGO_MAKE_WORKING_DIRECTORY}/librime/dist/include"
LIBRIME_LIB_DIR = "${CARGO_MAKE_WORKING_DIRECTORY}/librime/dist/lib"

[tasks.pre-build]
condition = { platforms = ["mac", "windows"], files_not_exist = ["${CARGO_MAKE_WORKING_DIRECTORY}/librime/version-info.txt"] }
run_task = { name = "fetch-rime-artifact" }

[tasks.fetch-rime-artifact]
mac_alias = "fetch-rime-artifact-mac"
windows_alias = "fetch-rime-artifact-windows"

[tasks.fetch-rime-artifact-mac]
env.rime_release = "1.17.0"
env.rime_artifact = "rime-33e7814-macOS-universal.tar.bz2"
env.rime_artifact_checksum = "11d8dc663c6ec06d5ccb6111ba664a9e7b631b703ac6acd07cffbac664021850"
run_task = { name = ["download-rime-artifact", "extract-rime-artifact-posix"] }

[tasks.fetch-rime-artifact-windows]
env.rime_release = "1.17.0"
env.rime_artifact = "rime-33e7814-Windows-msvc-x64.7z"
env.rime_artifact_checksum = "7478c7caa4ff6b37de86daba1f7ce4a994a4f5ba24872a820fb2b3a9b01fed15"
run_task = { name = ["download-rime-artifact", "extract-rime-artifact-windows"] }

[tasks.download-rime-artifact]
script_runner = "@duckscript"
script = '''
download_file = set ${CARGO_MAKE_WORKING_DIRECTORY}/${rime_artifact}
if not is_path_exists ${download_file}
  echo downloading ${rime_artifact}...
  response_size = http_client --output-file ${download_file} https://github.com/rime/librime/releases/download/${rime_release}/${rime_artifact}
  assert ${response_size}
  echo downloaded ${response_size} bytes to ${download_file}
else
  echo found ${download_file}
end
checksum = sha256sum ${download_file}
echo checksum: ${checksum}
assert_eq ${checksum} ${rime_artifact_checksum}
'''

[tasks.extract-rime-artifact-posix]
script = '''
mkdir -p "${CARGO_MAKE_WORKING_DIRECTORY}/librime"
tar -xjvf "${CARGO_MAKE_WORKING_DIRECTORY}/${rime_artifact}" -C "${CARGO_MAKE_WORKING_DIRECTORY}/librime"
'''

[tasks.extract-rime-artifact-windows]
command = "7z"
args = ["x", "-y", "-o${CARGO_MAKE_WORKING_DIRECTORY}/librime", "${CARGO_MAKE_WORKING_DIRECTORY}/${rime_artifact}"]
