name: commit-ci

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
    tags:
      - '*'
  workflow_dispatch:

jobs:

  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install cargo-make
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-make

      - name: Download librime artifact
        shell: bash
        run: |
          cargo make pre-build

      - name: Build
        run: |
          cargo make build-release

      # Test on Windows not ok yet
      #- name: Test
      #  run: |
      #    cargo test --release

      - name: Prepare package
        if: runner.os == 'Windows' || runner.os == 'macOS'
        run: |
          cargo make package-release

      - name: Archive production artifacts
        if: runner.os == 'Windows' || runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: rime-cli-${{ runner.os }}
          path: rime-cli-${{ runner.os }}${{ runner.os == 'Windows' && '.7z' || '.tar.gz' }}
